### ISSUE TITLE
Why image source format being RGBA instead of BGR. Also probable bug in aligner?

### ISSUE THREAD

**Issue by kafan1986** [MirrorYuChen/mnn_example#14]
In landmarker code, a previous change was reverted. May I know why? Seems like it should be BGR as per the testing code example, instead it is currently RGBA.

Also, for the aligner code for case 106:
https://github.com/MirrorYuChen/mnn_example/blob/fd213672f649a0de3b758389e9f99b02a3906206/src/face/aligner/aligner.cpp#L71
points_src[2] = keypoints[46]; // This should probably be keypoints[54], assuming this represent nose
and 106 keypoint correspond as per following https://arxiv.org/pdf/1905.03469.pdf

**Comment by MirrorYuChen** [comment]
其实都是可以的，之前那个有bug，所有revert了，关键点这里，我有时间再确认一下~

**Comment by kafan1986** [comment]
@MirrorYuChen https://github.com/MirrorYuChen/mnn_example/blob/206bdcf67f24ebcf2d3675ca39287ed08f65541a/src/face/test_face.cpp#L23
I still not sure why image source at below line is RGBA when you are reading image (img_src in above line) as BGR Mat.
https://github.com/MirrorYuChen/mnn_example/blob/d95563833ee9dec8773485464e003c604aea83f2/src/face/landmarker/zqlandmarker/zqlandmarker.cpp#L45

**Comment by MirrorYuChen** [comment]
其实都可以，你只有保证图像处理输入格式跟你的当前图片格式一致就行了，没啥好纠结的，具体内部会进行转换。

**Comment by MirrorYuChen** [comment]
等我有时间会再统一一次接口，最近真心忙，没时间。

**Comment by MirrorYuChen** [comment]
老哥有时间可以帮忙搞个android的项目吗？

**Comment by MirrorYuChen** [comment]
感觉C++还是差点意思。

**Comment by kafan1986** [comment]
@MirrorYuChen I am also very bust with my work. But If I get any time in future, I could help you with android project.

**Comment by MirrorYuChen** [comment]
ok，多谢啦~
