### ISSUE TITLE
用gpu时报错。  cpu能正常执行。

### ISSUE THREAD

**Issue by duoduo1018** [MirrorYuChen/mnn_example#15]
编译出vulkan版本的mnn.lib,   测试为1920*1080的图片
用cpu（MNN_FORWARD_CPU）会能正常执行，
但是用gpu（MNN_FORWARD_VULKAN）会报错，如下：
start detect.
Don't support too large feature: 960 x 528
Resize error for [Convolution], 363, code=2
Can't run session because not resized
end detect.

报错地址为： centerface_interpreter_->resizeSession(centerface_sess_);

当测试图片小(比如1024*768)的话，不会报错。该怎样修改呢？求大神指导，非常感谢

**Comment by MirrorYuChen** [comment]
错误翻译过来，不就是不支持太大的feature。

**Comment by MirrorYuChen** [comment]
具体不是很清楚，没跑过GPU

**Comment by LiYufengzz** [comment]
> 编译出vulkan版本的mnn.lib, 测试为1920*1080的图片
> 用cpu（MNN_FORWARD_CPU）会能正常执行，
> 但是用gpu（MNN_FORWARD_VULKAN）会报错，如下：
> start detect.
> Don't support too large feature: 960 x 528
> Resize error for [Convolution], 363, code=2
> Can't run session because not resized
> end detect.
> 
> 报错地址为： centerface_interpreter_->resizeSession(centerface_sess_);
> 
> 当测试图片小(比如1024*768)的话，不会报错。该怎样修改呢？求大神指导，非常感谢

请问大哥是怎么编译通过的，我的OpenCL和vulkan编译一直报错啊
