### ISSUE TITLE
meanVals_  ,normVals_    no use

### ISSUE THREAD

**Issue by alicera** [MirrorYuChen/mnn_example#16]
in the  mobilefacenet.h 
 const float meanVals_[3] = {     127.5f,     127.5f,     127.5f };
    const float normVals_[3] = { 0.0078125f, 0.0078125f, 0.0078125f };

but I cant see any use for  meanVals_ and normVals_

**Comment by kafan1986** [comment]
Some of the model have included the normalization step in the model itself. Open the model file using Netron or similar tool to check initial few layers of the model.

**Comment by alicera** [comment]
could you provide the mobilefacenet  .pth   link  before converting to .mnn, thanks

**Comment by kafan1986** [comment]
@alicera You are talking about face recognition model right? In that case, I believe the model here is originally trained by Insight face using arcface loss function optimization. You can go to insight face github repo and check it for yourself.

**Comment by MirrorYuChen** [comment]
https://github.com/MirrorYuChen/mnn_example/issues/8

**Comment by alicera** [comment]
thanks
