### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by mathpopo** [MirrorYuChen/mnn_example#17]
/home/chenxin/Downloads/mnn_example/src/classifier/classifier.h:25:10: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
     std::shared_ptr<MNN::Interpreter> classifier_interpreter_;
          ^~~~~~~~~~
/home/chenxin/Downloads/mnn_example/src/classifier/classifier.cpp: In destructor ‘mirror::Classifier::~Classifier()’:
/home/chenxin/Downloads/mnn_example/src/classifier/classifier.cpp:16:5: error: ‘classifier_interpreter_’ was not declared in this scope
     classifier_interpreter_->releaseModel();
     ^~~~~~~~~~~~~~~~~~~~~~~
/home/chenxin/Downloads/mnn_example/src/classifier/classifier.cpp: In member function ‘int mirror::Classifier::Init(const char*)’:
/home/chenxin/Downloads/mnn_example/src/classifier/classifier.cpp:23:5: error: ‘classifier_interpreter_’ was not declared in this scope
     classifier_interpreter_ = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFromFile(model_file.c_str()));
     ^~~~~~~~~~~~~~~~~~~~~~~
/home/chenxin/Downloads/mnn_example/src/classifier/classifier.cpp:23:31: error: ‘shared_ptr’ is not a member of ‘std’
     classifier_interpreter_ = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFromFile(model_file.c_str()));
                               ^~~
/home/chenxin/Downloads/mnn_example/src/classifier/classifier.cpp:23:63: error: expected primary-expression before ‘>’ token
     classifier_interpreter_ = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFromFile(model_file.c_str()));
                                                               ^
/home/chenxin/Downloads/mnn_example/src/classifier/classifier.cpp: In member function ‘int mirror::Classifier::Classify(const cv::Mat&, std::vector<mirror::ImageInfo>*)’:
/home/chenxin/Downloads/mnn_example/src/classifier/classifier.cpp:65:5: error: ‘shared_ptr’ is not a member of ‘std’
     std::shared_ptr<MNN::CV::ImageProcess> pretreat(
     ^~~
/home/chenxin/Downloads/mnn_example/src/classifier/classifier.cpp:65:42: error: expected primary-expression before ‘>’ token
     std::shared_ptr<MNN::CV::ImageProcess> pretreat(
                                          ^
/home/chenxin/Downloads/mnn_example/src/classifier/classifier.cpp:67:5: error: ‘pretreat’ was not declared in this scope
     );
     ^
/home/chenxin/Downloads/mnn_example/src/classifier/classifier.cpp:71:5: error: ‘classifier_interpreter_’ was not declared in this scope
     classifier_interpreter_->runSession(classifier_sess_);
     ^~~~~~~~~~~~~~~~~~~~~~~
CMakeFiles/VisionEngine.dir/build.make:75: recipe for target 'CMakeFiles/VisionEngine.dir/classifier/classifier.cpp.o' failed
make[2]: *** [CMakeFiles/VisionEngine.dir/classifier/classifier.cpp.o] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/VisionEngine.dir/all' failed
make[1]: *** [CMakeFiles/VisionEngine.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by MirrorYuChen** [comment]
别一上来就贴一堆错误，首先，请确认一下是否按照readme里面的操作流程操作，然后，提供边缘的平台信息，再才是错误。

**Comment by MirrorYuChen** [comment]
长时间未见回复，默认已经解决。

**Comment by zhcv** [comment]
@mathpopo  I have the same problem as you. Have you solved it？

**Comment by zhcv** [comment]
@MirrorYuChen  环境   gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4， MNN 除啦converter, 其它均可正常编译

**Comment by MirrorYuChen** [comment]
需要在你自己的平台上编译mnn，然后替换掉工程中的mnn库~

**Comment by MirrorYuChen** [comment]
我这个是在jetson nano上编译的mnn库~应该不通用~

**Comment by zhcv** [comment]
> 需要在你自己的平台上编译mnn，然后替换掉工程中的mnn库~

库是在自己平台上编译的，可正常使用

**Comment by MirrorYuChen** [comment]
有替换掉项目中的mnn库吗？

**Comment by zhcv** [comment]
@MirrorYuChen  替换过啦

**Comment by zhcv** [comment]
不是库的问题， In file included from /data1/MNN-DEMO/mnn_example/src/classifier/classifier.cpp:1:0:
/data1/MNN-DEMO/mnn_example/src/classifier/classifier.h:25:5: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
     std::shared_ptr<MNN::Interpreter> classifier_interpreter_;
     ^
/data1/MNN-DEMO/mnn_example/src/classifier/classifier.cpp: In destructor ‘mirror::Classifier::~Classifier()’:
/data1/MNN-DEMO/mnn_example/src/classifier/classifier.cpp:16:5: error: ‘classifier_interpreter_’ was not declared in this scope
     classifier_interpreter_->releaseModel();
     ^
/data1/MNN-DEMO/mnn_example/src/classifier/classifier.cpp: In member function ‘int mirror::Classifier::Init(const char*)’:
/data1/MNN-DEMO/mnn_example/src/classifier/classifier.cpp:23:5: error: ‘classifier_interpreter_’ was not declared in this scope
     classifier_interpreter_ = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFromFile(model_file.c_str()));
     ^
/data1/MNN-DEMO/mnn_example/src/classifier/classifier.cpp:23:31: error: ‘shared_ptr’ is not a member of ‘std’
     classifier_interpreter_ = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFromFile(model_file.c_str()));
                               ^
/data1/MNN-DEMO/mnn_example/src/classifier/classifier.cpp:23:63: error: expected primary-expression before ‘>’ token
     classifier_interpreter_ = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFromFile(model_file.c_str()));
                                                               ^
/data1/MNN-DEMO/mnn_example/src/classifier/classifier.cpp: In member function ‘int mirror::Classifier::Classify(const cv::Mat&, std::vector<mirror::ImageInfo>*)’:
/data1/MNN-DEMO/mnn_example/src/classifier/classifier.cpp:65:5: error: ‘shared_ptr’ is not a member of ‘std’
     std::shared_ptr<MNN::CV::ImageProcess> pretreat(

**Comment by MirrorYuChen** [comment]
贴一下错误~

**Comment by MirrorYuChen** [comment]
C++ 11 没打开吗？std::shared_ptr不能识别

**Comment by zhcv** [comment]
打开啦

**Comment by MirrorYuChen** [comment]
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -fPIC -O3 -std=c++11 -fopenmp") 我这里也打开了啊，很奇怪的错误，我周末有时间看一下~

**Comment by zhcv** [comment]
好的，

> set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -fPIC -O3 -std=c++11 -fopenmp") 我这里也打开了啊，很奇怪的错误，我周末有时间看一下~

好

**Comment by MirrorYuChen** [comment]
再次确认一下环境：Ubuntu 14.04，gcc 4.8.4

**Comment by zhcv** [comment]
> 再次确认一下环境：Ubuntu 14.04，gcc 4.8.4

@MirrorYuChen  @mathpopo  问题已解决，缺少头文件 #include<memory>

https://stackoverflow.com/questions/28914711/getting-error-shared-ptr-in-namespace-std-does-not-name-a-type

**Comment by MirrorYuChen** [comment]
#include <memory>这样就行了是吧？你这边能PR一下吗？

**Comment by MirrorYuChen** [comment]
#include <memory>  ？ 能不能PR一下？

**Comment by MirrorYuChen** [comment]
memory头文件？能不能PR一下，谢谢~

**Comment by MirrorYuChen** [comment]
ok, 3Q~
