### ISSUE TITLE
Memory leak while running zqlandmarker

### ISSUE THREAD

**Issue by kafan1986** [MirrorYuChen/mnn_example#19]
The ultraface seems to be leaking memory when run on 2 or more number of threads. It seems to be OK, when only 1 thread is used.

https://github.com/MirrorYuChen/mnn_example/blob/d95563833ee9dec8773485464e003c604aea83f2/src/face/detecter/ultraface/ultraface.cpp#L35

For the ZQLandmarker it leaks memory even with default 1 thread configuration.

Can you please check and confirm this at your end? By running the ZQLandmarker number of times in loop.

**Comment by MirrorYuChen** [comment]
啥平台测试的啊？MNN库本身是否存在这个问题？

**Comment by MirrorYuChen** [comment]
坐等官方人员回复吧，应该不是我的锅~

**Comment by MirrorYuChen** [comment]
没有在android上测试过。

**Comment by kafan1986** [comment]
@MirrorYuChen I have posted an error thread on official MNN github. Yes, the error is observed in android, I haven't setup MNN on my PC. If you can confirm whether you observe it the same at your end, may be on PC, it will help.

**Comment by MirrorYuChen** [comment]
没时间弄~

**Comment by kafan1986** [comment]
Closing as I have raised the issue with MNN team.

**Comment by MirrorYuChen** [comment]
@xuguozhi

**Comment by MirrorYuChen** [comment]
老哥有时间帮忙看一下~

**Comment by xuguozhi** [comment]
Fine

**Comment by kafan1986** [comment]
I have posted android test app on https://github.com/alibaba/MNN/issues/888

**Comment by alicera** [comment]
有docker 的环境可模拟Android 吗？
我也想复现在手机上找問題

**Comment by MirrorYuChen** [comment]
你这里new完之后，没有delete掉，可以再写一个析构函数，用来释放内存。
![image](https://user-images.githubusercontent.com/49817428/84864016-904a3c80-b0a8-11ea-9c08-6a3335d0ad48.png)

**Comment by xuguozhi** [comment]
> 你这里new完之后，没有delete掉，可以再写一个析构函数，用来释放内存。
> ![image](https://user-images.githubusercontent.com/49817428/84864016-904a3c80-b0a8-11ea-9c08-6a3335d0ad48.png)

应该是这里

**Comment by xuguozhi** [comment]
> 有docker 的环境可模拟Android 吗？
> 我也想复现在手机上找問題

用模拟器吧，读视频文件

**Comment by MirrorYuChen** [comment]
你可以参考我写的test程序：
![image](https://user-images.githubusercontent.com/49817428/84864351-1ebebe00-b0a9-11ea-9abd-d4954d4a3626.png)

**Comment by MirrorYuChen** [comment]
感觉我有时间得自己学一下android。

**Comment by xuguozhi** [comment]
delete之前判断下是否为nullptr
粗略看下jni这里 :
`static inline JNI_FACEDETECT *jniFaceDetect = NULL;`
`jniFaceDetect = new JNI_FACEDETECT;` 也没有手动删除

**Comment by kafan1986** [comment]
> Before deleting , determine whether it is nullptr. Look
> at jni here:
> `static inline JNI_FACEDETECT *jniFaceDetect = NULL;`
> `jniFaceDetect = new JNI_FACEDETECT;`there is no manual deletion.

Yes, but in this case it won't matter much as the jniFaceDetect is only created once, so there should not be any continuous memory leak.

    ```
void LoadJniFaceDetect(JNIEnv *env) {

        **if (jniFaceDetect != NULL)
            return;**

        jniFaceDetect = new JNI_FACEDETECT;

```

**Comment by kafan1986** [comment]
> After you finish new here, there is no delete, you can write another destructor to release memory.
> ![image](https://user-images.githubusercontent.com/49817428/84864016-904a3c80-b0a8-11ea-9c08-6a3335d0ad48.png)

I reuse the same object again and again. Yes, I should put the delete in the DestroyEngine code but currently there should not be any memory leak because of this. You can disable the landmark generation part and make the ultra face detection thread count to 1 and there won't be any more memory leak.

`m_hEngineHandle = PeopleCountingEngine.CreateEngine(jszPath_Detecter_Ultraface, detecterNumThreads, jszPath_Landmarker, landmarkerNumThreads);`

**Comment by xuguozhi** [comment]
> Yes, I should put the delete in the DestroyEngine code but currently there should not be any memory leak because of this. You can disable the landmark generation part and make the ultra face detection thread count to 1 and there won't be an

have you ever try video Camera as input data and check the memory status?

**Comment by kafan1986** [comment]
> > Yes, I should put the delete in the DestroyEngine code but currently there should not be any memory leak because of this. You can disable the landmark generation part and make the ultra face detection thread count to 1 and there won't be an
> 
> have you ever try video Camera as input data and check the memory status?

Yes, there is still memory leak.

**Comment by kafan1986** [comment]
@xuguozhi I have changed the numThreads for ultraface detection to 1 and disabled the landmark detection in the attached code. You can see there is no more leak, if you build the app.

[MNNMemoryLeakTest.zip](https://github.com/MirrorYuChen/mnn_example/files/4792176/MNNMemoryLeakTest.zip)

**Comment by kafan1986** [comment]
Solved it on my own.

**Comment by xuguozhi** [comment]
> Solved it on my own.

Is there anything you want to share with us?

**Comment by MirrorYuChen** [comment]
如何解决的能否说明一下？

**Comment by kafan1986** [comment]
I did 3 changes, but I believe 2nd one helped remove the bug.

 1) resizeSession has to be used post resizeTensor, according to MNN docs.
```
        zq_interpreter_->resizeTensor(input_tensor_, {1, 3, inputSize_.height, inputSize_.width});
        zq_interpreter_->resizeSession(zq_sess_); 

```
2) Do not use GetImage rather convert the image data in following way to tensor.
```
       cv::resize(img_face, img_resized, inputSize_);
       //     uint8_t *data_ptr = GetImage(img_resized); 
       pretreat_->convert(img_resized.data, inputSize_.width, inputSize_.height, 0, input_tensor_);
```

3) Now it works correctly with sourceFormat as RGB and doesn't with previous RGBA or as the original image format (if you are using BGR mat, then use BGR).
```
        img_config.sourceFormat = MNN::CV::RGB;
        img_config.destFormat = MNN::CV::RGB;
```

**Comment by MirrorYuChen** [comment]
好的，我这周的周末处理一下。

**Comment by xuguozhi** [comment]
https://github.com/MirrorYuChen/mnn_example/issues/9

**Comment by MirrorYuChen** [comment]
找到原因了，这个地方要释放掉内存：delete pImg
![image](https://user-images.githubusercontent.com/49817428/85095348-b2b49500-b223-11ea-9d6d-496f0a43a910.png)

**Comment by MirrorYuChen** [comment]
convert之后要释放掉申请的内存。

**Comment by xuguozhi** [comment]
@MirrorYuChen 
 https://github.com/MirrorYuChen/mnn_example/blob/master/src/common/common.cpp#L10
`uchar* data_ptr = new uchar[img_src.total() * 4];` new的data_ptr 要手动delete吧

**Comment by MirrorYuChen** [comment]
嗯嗯，太麻烦了，这周周末修一下，把GetImage接口剔除掉。

**Comment by xuguozhi** [comment]
> 嗯嗯，太麻烦了，这周周末修一下，把GetImage接口剔除掉。

用这句替换吧`pretreat_->convert(img_resized.data, inputSize_.width, inputSize_.height, 0, input_tensor_);` 但是用到GetImage的地方比较多，改过后要回归测试一边效果，应该问题不大

**Comment by MirrorYuChen** [comment]
已经修了~
