### ISSUE TITLE
人脸检测 Ultraface也可以合并进来

### ISSUE THREAD

**Issue by xuguozhi** [MirrorYuChen/mnn_example#2]
hi，这里的人脸检测也不错，很适合在移动端部署，https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/MNN

**Comment by MirrorYuChen** [comment]
周末再弄一下吧，感觉utraface里面代码有点乱，周末再仔细看一下~

**Comment by deep-practice** [comment]
mnn和ncnn哪个框架更适合移动端?

**Comment by xuguozhi** [comment]
> mnn和ncnn哪个框架更适合移动端?

看个人喜好，ncnn社区成熟，样例比较多。mnn后起之秀，较有潜力

**Comment by MirrorYuChen** [comment]
其实我更喜欢ncnn，代码风格啥的都非常不错，MNN这接口设计的，感觉参考了tensorflow lite，数据输入接口看着蛋疼~

**Comment by MirrorYuChen** [comment]
已经添加ultraface代码，大家可以测试一下~

**Comment by xuguozhi** [comment]
采用slim.mnn 分辨率可设置为160*120，嵌入式运行OK；但是slim的量化模型得不到结果。目标平台 ：Android
