### ISSUE TITLE
Mobilefacenet example (TestRecognizer) in test_face.cpp output results seems weird?

### ISSUE THREAD

**Issue by rena-ganba** [MirrorYuChen/mnn_example#21]
When I use TestRecognizer function in test_face.cpp, the results seems wrong. It always makes output consistently like this:

similarity is: 0.793833

Whatever pair of face I input, even for same images. Something wrong with it?

**Comment by MirrorYuChen** [comment]
I need to check it later.

**Comment by MirrorYuChen** [comment]
我这边测试了一下，没有出现这种情况啊，你给两张照片我测试一下~
