### ISSUE TITLE
image process pro ?

### ISSUE THREAD

**Issue by alicera** [MirrorYuChen/mnn_example#22]
cv::resize(img_src.clone(), img_resized, inputSize_);
why ,you do the img_src.clone()  instead of img_src

我想了解一下 为什么 convert 要用(uint8_t*) 谢谢 
    pretreat->convert((uint8_t*)img_resized.data, inputSize_.width, inputSize_.height, img_resized.step[0], input_tensor_);

**Comment by MirrorYuChen** [comment]
clone的原因是，保证不去修改传入数据，可以不用强制转换。
