### ISSUE TITLE
编译错误，帮忙看看

### ISSUE THREAD

**Issue by liuwei3612** [MirrorYuChen/mnn_example#24]
../../src/../lib/libMNN.so: 无法添加符号: 文件格式错误
collect2: error: ld returned 1 exit status
src/CMakeFiles/object.dir/build.make:113: recipe for target 'src/object' failed
make[2]: *** [src/object] Error 1
CMakeFiles/Makefile2:91: recipe for target 'src/CMakeFiles/object.dir/all' failed
make[1]: *** [src/CMakeFiles/object.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by MirrorYuChen** [comment]
https://github.com/MirrorYuChen/mnn_example/issues/17

**Comment by MirrorYuChen** [comment]
看一下这个~

**Comment by MirrorYuChen** [comment]
需要替换一下库
