### ISSUE TITLE
Did you ever benchmark MNN on x86 vs other framework?

### ISSUE THREAD

**Issue by kafan1986** [MirrorYuChen/mnn_example#25]
I am building an app that will run on server environment and might be CPU only environment. What is the performance of MNN framework vs other popular CPU optimized framework like OpenCV DNN etc?

**Comment by MirrorYuChen** [comment]
不清楚，没测试过~

**Comment by kafan1986** [comment]
> I don’t know, I haven’t tested it~

But you built the application on PC, I believe. How is the inference performance compared to inference of same model on framework like tensorflow or opencv DNN?

**Comment by MirrorYuChen** [comment]
说了没测就是没测，这个项目只是我用来练手的，我也没责任和义务帮你测试。
