### ISSUE TITLE
执行./face时出错

### ISSUE THREAD

**Issue by 205418367** [MirrorYuChen/mnn_example#26]
在ubuntu18.04平台编译，出错内容如下：
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted

怎么解决呢？

**Comment by leemengxing** [comment]
hello,怎么解决呢？方便给个方案嘛

**Comment by leemengxing** [comment]
传个pic的参数就行。
