### ISSUE TITLE
 make -j3   error

### ISSUE THREAD

**Issue by linzhongchen** [MirrorYuChen/mnn_example#27]
(Mnn) wzlock@wzlock-Precision-7920-Tower:~/lin/pytorch/mnn_example/build$ make -j3
[  4%] Building CXX object src/CMakeFiles/VisionEngine.dir/common/common.cpp.o
[  8%] Building CXX object src/CMakeFiles/VisionEngine.dir/classifier/classifier.cpp.o
[ 12%] Building CXX object src/CMakeFiles/VisionEngine.dir/object/mobilenetssd/mobilenetssd.cpp.o
In file included from /home/wzlock/lin/pytorch/mnn_example/src/common/common.cpp:1:0:
/home/wzlock/lin/pytorch/mnn_example/src/common/common.h:7:28: fatal error: opencv2/core.hpp: 没有那个文件或目录
compilation terminated.
src/CMakeFiles/VisionEngine.dir/build.make:62: recipe for target 'src/CMakeFiles/VisionEngine.dir/common/common.cpp.o' failed
make[2]: *** [src/CMakeFiles/VisionEngine.dir/common/common.cpp.o] Error 1
make[2]: *** 正在等待未完成的任务....
In file included from /home/wzlock/lin/pytorch/mnn_example/src/object/mobilenetssd/mobilenetssd.cpp:1:0:
/home/wzlock/lin/pytorch/mnn_example/src/object/mobilenetssd/mobilenetssd.h:12:28: fatal error: opencv2/core.hpp: 没有那个文件或目录
compilation terminated.
src/CMakeFiles/VisionEngine.dir/build.make:110: recipe for target 'src/CMakeFiles/VisionEngine.dir/object/mobilenetssd/mobilenetssd.cpp.o' failed
make[2]: *** [src/CMakeFiles/VisionEngine.dir/object/mobilenetssd/mobilenetssd.cpp.o] Error 1
In file included from /home/wzlock/lin/pytorch/mnn_example/src/classifier/classifier.cpp:1:0:
/home/wzlock/lin/pytorch/mnn_example/src/classifier/classifier.h:13:28: fatal error: opencv2/core.hpp: 没有那个文件或目录
compilation terminated.
src/CMakeFiles/VisionEngine.dir/build.make:86: recipe for target 'src/CMakeFiles/VisionEngine.dir/classifier/classifier.cpp.o' failed
make[2]: *** [src/CMakeFiles/VisionEngine.dir/classifier/classifier.cpp.o] Error 1
CMakeFiles/Makefile2:91: recipe for target 'src/CMakeFiles/VisionEngine.dir/all' failed
make[1]: *** [src/CMakeFiles/VisionEngine.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by MirrorYu** [comment]
系统没有装OpenCV，自己源码安装一下OpenCV就好了
