### ISSUE TITLE
请问大佬pfld模型怎么获取的啊？效果如何啊

### ISSUE THREAD

**Issue by DuckJ** [MirrorYuChen/mnn_example#3]

**Comment by MirrorYuChen** [comment]
直接从MNN_APLICATION项目里面拿过来的 https://github.com/xindongzhang/MNN-APPLICATIONS，感觉效果不是很好

**Comment by DuckJ** [comment]
谢谢回复，原项目好像在[这里](https://github.com/ailab26/pfld-lite)
对了，大佬觉得zuoqing 106的模型如何啊，我去年试了你转的左博那个106模型，感觉效果也不太好啊

**Comment by MirrorYuChen** [comment]
那不能怪我呀，我就是提供调用，效果好不好我不背责任的

**Comment by MirrorYuChen** [comment]
你说的那个项目跟我说的这个是一个作者

**Comment by MirrorYuChen** [comment]
我提供mnn_example这个项目，只是为了帮助大家使用mnn，至于说效果，都是开源的模型，我没法保证的~

**Comment by MirrorYuChen** [comment]
https://github.com/zuoqing1988/ZQCNN/issues/131
