### ISSUE TITLE
A potential memory leak problem

### ISSUE THREAD

**Issue by yanren1** [MirrorYuChen/mnn_example#30]
You probobly need to release the Tensor in mobilefacenet.cpp line 64 (nhwc_tensor) after line 68 as MNN suggested. Or we may face memory leak problem when you loop this function. And thank you so much for your work.

**Comment by MirrorYuChen** [comment]
Yes, You are right! Can you make a pull request to fix it?

**Comment by MirrorYuChen** [comment]
Thanks~
