### ISSUE TITLE
how to config if i have two models

### ISSUE THREAD

**Issue by Liujingxiu23** [MirrorYuChen/mnn_example#32]
For help!
Your app seems more complicated than mine. My subject is not face dection, I only have two mnn models,  somethings like encoder and decoder.
How can I do config of mnn models to improve the speed and avoid memory leak?
The two models is runned sequentially, first encoder and tehn decoder

**Comment by MirrorYuChen** [comment]
All right! You can refer to the part of the content of the LoadModel interface.  At the same  time, the ducument of the mnn also  work!
