### ISSUE TITLE
error in compiling

### ISSUE THREAD

**Issue by yanwenbit** [MirrorYuChen/mnn_example#34]
When I make this project, it shows "../../src/../lib/libMNN.so: error adding symbols: File in wrong format". So I should recompile libMNN.so in my system, right? How could I compile this file? Thanks!

**Comment by LiYufengzz** [comment]
what is your system?

**Comment by goodzhangbobo** [comment]
hello, I  encounter  the  same error. My system is Ubuntu 16.04.
Could you help me to resolve it .

**Comment by goodzhangbobo** [comment]
I progressed it with commands like:  
```
$mkdir  build
$cd build
$cmake  ..
$make  -j4
```
then the error happened.

**Comment by MirrorYuChen** [comment]
把MNN库替换成你自己系统上编译的，然后再重新编译一下就可以了
