### ISSUE TITLE
Face Alignment code is giving me weird result.

### ISSUE THREAD

**Issue by kafan1986** [MirrorYuChen/mnn_example#5]
I am using the alignment code and although it fixes the rotation but there is lots of extra black padding on the image. Is this the expected outcome of the alignment operation?

![WhatsApp Image 2020-03-18 at 4 02 52 PM](https://user-images.githubusercontent.com/7953422/76952204-c30e5880-6932-11ea-858c-2e94cd731b36.png)

**Comment by MirrorYuChen** [comment]
yes，I have the same result before, I'll check it later this week~

**Comment by kafan1986** [comment]
@MirrorYuChen I did come with some solution. The aligner uses these values for 112x112 face size:

```
		{ 30.2946f + 8.0f, 51.6963f }, // left eye
		{ 65.5318f + 8.0f, 51.5014f }, // right eye
		{ 48.0252f + 8.0f, 71.7366f }, // nose tip
		{ 33.5493f + 8.0f, 92.3655f }, // left mouth corner
		{ 62.7299f + 8.0f, 92.2041f }  // right mouth corner
```

But as I am using MTCNN to detect the face box and keypoints, I looked at the face rect shape and size and then referenced below data
http://www.beginnersschool.com/2015/08/21/facial-proportions-and-sculpting-a-face/
and calculated to come up with new values that works with MTCNN better.

```
		{ 35.41f, 47.15f}, // left eye
		{ 78.23f, 47.15f}, // right eye
		{ 56.41f, 69.16f}, // nose tip
		{ 39.11f, 88.81f }, // left mouth corner
		{ 72.47f, 88.81f}  // right mouth corner
```

With these values the aligner works better and it does not distorts human face shape and size and aspect ratio etc.

But now I think all other models, e.g. arcface, mobilefacenet  etc., universally uses the above alignment values. And in next step, if one needs to use the above aligned face data with different models "effectively", one would need to retrain the models again. Not sure what would be drop in accuracy of models, if it is directly used with new aligned face data.

**Comment by MirrorYuChen** [comment]
Not quick right! I think it should be aligned from source image, not the face, you can refer to my ncnn_example(!https://github.com/MirrorYuChen/ncnn_example) project. Than i need to change the interface of landmarker detecter.

**Comment by MirrorYuChen** [comment]
I'll check this week,.

**Comment by MirrorYuChen** [comment]
fixed, you can check the new code.

**Comment by kafan1986** [comment]
You didn't change much in the Aligner rather you tweaked the keypoint's position and adjusted it with the face's location. Am I right? Can you check what is aligned face output for profile face pics?

**Comment by MirrorYuChen** [comment]
In fact， there's no error in aligner methold itself. I have changed nothing in face aligner. but the usage of the process. The bad result come from the error usage.

**Comment by MirrorYuChen** [comment]
You can check the result of the new code.

**Comment by MirrorYuChen** [comment]
![image](https://user-images.githubusercontent.com/49817428/77219484-2a195080-6b71-11ea-97ab-e95e212d3269.png)

**Comment by MirrorYuChen** [comment]
what's reason? I think it's not a difficult problem, you can figure out according to the code. enjoy!
