### ISSUE TITLE
sourceFormat RGBA

### ISSUE THREAD

**Issue by xuguozhi** [MirrorYuChen/mnn_example#6]
https://github.com/MirrorYuChen/mnn_example/blob/fd213672f649a0de3b758389e9f99b02a3906206/src/face/landmarker/pfldlandmarker/pfldlandmarker.cpp#L46
如果在移动端Android/IOS 传进来是RGBA的模式，没错；
但如果是Linux嵌入式，sourceFormat应该是BGR？虽然可视化结果可能没啥区别

**Comment by MirrorYuChen** [comment]
老哥，你提个PR修一下~

**Comment by xuguozhi** [comment]
git 太慢 居然在公司都拉不下来，直接在网页上改了。

**Comment by MirrorYuChen** [comment]
ok~
