### ISSUE TITLE
NHWC or NCHW format for mobilefacenet?

### ISSUE THREAD

**Issue by kafan1986** [MirrorYuChen/mnn_example#8]
https://github.com/MirrorYuChen/mnn_example/blob/c79c6388c18742f9af426522e27f739300c0086f/src/face/recognizer/mobilefacenet/mobilefacenet.cpp#L62

Can you tell me why have you used the NHWC format rather than NCHW format?

**Comment by MirrorYuChen** [comment]
自己研究一下imagprocess代码吧~

**Comment by kafan1986** [comment]
> 自己研究一下imagprocess代码吧~

Did take a look and it looks like, it internally takes care of it.

I have another question, for the face recognition using mobilefacenet, do we need to perform standardization? Asking because you have skipped it.

**Comment by MirrorYuChen** [comment]
模型内部做了，不需要~

**Comment by MirrorYuChen** [comment]
自己用MNN的工具dump一下模型看看~

**Comment by kafan1986** [comment]
@

> Use the MNN tool to dump the model yourself to see ~
Yes, just checked the model. Found it. Thanks.

**Comment by kafan1986** [comment]
@MirrorYuChen I have another question. I am using arcface for face recognition with mnn. (originally trained using mxnet). I have converted the params and json file to onnx and then to mnn.

I believe the mxnet uses NCHW format as default. So can you guide me how to create input tensor for NCHW format with image data? Is their an example here where you did the same? I believe for ultraface you are doing the same. (A) Can you confirm it? Also, my model has standardization in the model. So to skip it, (B) should I set the config mean value as 0 and norm multiplier as 1?

**Comment by MirrorYuChen** [comment]
Please provide your model, Your python Test code.

**Comment by MirrorYuChen** [comment]
My email address: 15671640320@163.com

**Comment by kafan1986** [comment]
Solved it. Your code is fine.
