### ISSUE TITLE
windows下人脸检测不准

### ISSUE THREAD

**Issue by zhongwenkun886** [MirrorYuChen/mnn_example#9]
![无标题](https://user-images.githubusercontent.com/42397285/78737805-00d72d80-7983-11ea-9f18-3667705f4791.png)

**Comment by MirrorYuChen** [comment]
这明显就是不对，而不是不准，我有时间再测试一下吧，具体不清楚~

**Comment by MirrorYuChen** [comment]
@xuguozhi 你改过之后，在windows上出现问题了，你检查一下，我先回撤到上一版本，上一个版本没有问题。

**Comment by MirrorYuChen** [comment]
@zhongwenkun886 你测试一下新的，我revert了一下，刚才测试了一下发现上一个版本没问题。

**Comment by MirrorYuChen** [comment]
@xuguozhi 我周末再看一下是什么问题~

**Comment by xuguozhi** [comment]
我也看看

**Comment by MirrorYuChen** [comment]
嗯嗯，好的

**Comment by xuguozhi** [comment]
bug 复现，原因找到：https://github.com/MirrorYuChen/mnn_example/blob/master/src/common/common.cpp#L9
预处理时调用该函数强制将图像转换成RGBA格式。

**Comment by MirrorYuChen** [comment]
这个之前这么写的原因是把所有数据读入方式都涵盖在项目中，还有创建tensor的方式，直接从opencv的Mat读入的方式

**Comment by xuguozhi** [comment]
`pretreat_->convert(img_resized.data, inputSize_.width, inputSize_.height, 0, input_tensor_);` 
即可，先就这样不改动了吧，因为其他的算法也要用GetImage。

**Comment by MirrorYuChen** [comment]
嗯嗯，等下个版本加tracker，更新landmarker时，再把这种接口剔除掉

**Comment by zhongwenkun886** [comment]
OK，谢谢各位
